# Reduction to Hessenberg form

The upper-triangular Hessenberg form has zeros below the first sub-diagonal

$$
\begin{bmatrix}
* & * & * & * & * & * \\
* & * & * & * & * & * \\
0 & * & * & * & * & * \\
0 & 0 & * & * & * & * \\
0 & 0 & 0 & * & * & * \\
0 & 0 & 0 & 0 & * & * \\
\end{bmatrix}
$$

In [1]:
import numpy as np

In [2]:
# We need sign function with sign(0) = 1
def sign(x):
    if x >= 0.0:
        return 1.0
    else:
        return -1.0

# Algorithm 26.1
def hessenberg(A):
    m = A.shape[0]
    for k in range(m-2):
        x = A[k+1:m, k]
        e1 = np.zeros_like(x)
        e1[0] = 1.0
        v = sign(x[0]) * np.linalg.norm(x) * e1 + x
        v = v / np.linalg.norm(v)
        A[k+1:m,k:m] = A[k+1:m,k:m] - 2.0 * np.outer(v, np.dot(v, A[k+1:m,k:m]))
        A[0:m,k+1:m] = A[0:m,k+1:m] - 2.0 * np.outer(A[0:m,k+1:m] @ v, v)
    return A

Test on a random matrix.

In [3]:
m = 7
A = np.random.rand(m,m)
H = hessenberg(A)
print(np.array_str(H, precision=2))

[[ 8.19e-01 -1.77e+00 -5.47e-03 -4.16e-01 -3.43e-01  2.17e-01  2.99e-01]
 [-1.77e+00  2.66e+00  3.26e-01  3.47e-01  4.29e-01  3.84e-01 -8.53e-02]
 [ 5.55e-17  1.12e+00 -2.32e-01 -1.75e-01 -9.08e-02  4.57e-01 -5.22e-02]
 [ 1.11e-16  0.00e+00 -3.32e-01 -3.05e-01 -4.36e-01 -1.38e-01  2.47e-01]
 [ 0.00e+00  0.00e+00  0.00e+00  7.32e-01  8.65e-02 -2.46e-01  1.22e-01]
 [-1.11e-16  0.00e+00  0.00e+00  0.00e+00 -1.82e-01 -1.28e-01  6.11e-01]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  3.47e-18 -5.79e-01 -6.70e-02]]


Extract the lower triangular part which is supposed to be zero.

In [4]:
L = np.tril(H,k=-2)
print(np.array_str(L, precision=2))

[[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 5.55e-17  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 1.11e-16  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [-1.11e-16  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  3.47e-18  0.00e+00  0.00e+00]]


Compute the maximum over the zero elements.

In [5]:
print(np.abs(L).max())

1.1102230246251565e-16


Test on a larger matrix without printing.

In [6]:
m = 100
A = np.random.rand(m, m)
H = hessenberg(A)
L = np.tril(H,k=-2)
print(np.abs(L).max())

8.881784197001252e-16
