# Reduction to Hessenberg form

The upper-triangular Hessenberg form has zeros below the first sub-diagonal

$$
\begin{bmatrix}
* & * & * & * & * & * \\
* & * & * & * & * & * \\
0 & * & * & * & * & * \\
0 & 0 & * & * & * & * \\
0 & 0 & 0 & * & * & * \\
0 & 0 & 0 & 0 & * & * \\
\end{bmatrix}
$$

In [1]:
import numpy as np

In [2]:
# We need sign function with sign(0) = 1
def sign(x):
    if x >= 0.0:
        return 1.0
    else:
        return -1.0

# Algorithm 26.1
def hessenberg(A):
    m = A.shape[0]
    for k in range(m-2):
        x = A[k+1:m, k]
        e1 = np.zeros_like(x)
        e1[0] = 1.0
        v = sign(x[0]) * np.linalg.norm(x) * e1 + x
        v = v / np.linalg.norm(v)
        A[k+1:m,k:m] = A[k+1:m,k:m] - 2.0 * np.outer(v, np.dot(v, A[k+1:m,k:m]))
        A[0:m,k+1:m] = A[0:m,k+1:m] - 2.0 * np.outer(A[0:m,k+1:m] @ v, v)
    return A

Test on a random matrix.

In [3]:
m = 7
A = np.random.rand(m,m)
H = hessenberg(A)
print(np.array_str(H, precision=2))

[[ 6.41e-01 -1.19e+00 -6.06e-01  1.22e-01  5.97e-02 -2.07e-01 -2.26e-01]
 [-1.40e+00  2.50e+00  1.49e+00 -1.82e-02 -1.19e-01 -2.91e-01 -5.98e-01]
 [ 0.00e+00  1.33e+00  4.47e-01  2.82e-01 -3.55e-01  3.57e-01  1.43e-01]
 [ 0.00e+00  0.00e+00  6.07e-01  9.64e-02  3.53e-01  5.64e-01 -5.65e-01]
 [ 0.00e+00  0.00e+00  2.78e-17  8.61e-01  8.42e-02  2.32e-01  1.89e-01]
 [ 0.00e+00  0.00e+00  5.55e-17 -1.11e-16 -1.36e-01 -1.25e-01 -1.40e-01]
 [ 0.00e+00  0.00e+00  5.55e-17  5.55e-17 -2.78e-17 -2.18e-03 -5.96e-02]]


Extract the lower triangular part which is supposed to be zero.

In [4]:
L = np.tril(H,k=-2)
print(np.array_str(L, precision=2))

[[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  2.78e-17  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  5.55e-17 -1.11e-16  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00  5.55e-17  5.55e-17 -2.78e-17  0.00e+00  0.00e+00]]


Compute the maximum over the zero elements.

In [5]:
print(np.abs(L).max())

1.1102230246251565e-16


Test on a larger matrix without printing.

In [6]:
m = 100
A = np.random.rand(m, m)
H = hessenberg(A)
L = np.tril(H,k=-2)
print(np.abs(L).max())

1.7763568394002505e-15


## Hermitian case

In this case, the Hessenberg reduction should give a tridiagonal matrix.

In [8]:
m = 7
A = np.random.rand(m,m)
A = 0.5 * (A + A.T)
H = hessenberg(A)
print(np.array_str(H, precision=2, suppress_small=True))

[[ 0.33 -1.26 -0.   -0.    0.   -0.   -0.  ]
 [-1.26  2.8  -0.7   0.   -0.   -0.    0.  ]
 [ 0.   -0.7   0.18 -0.45 -0.    0.    0.  ]
 [ 0.    0.   -0.45  0.28  0.61 -0.   -0.  ]
 [ 0.    0.    0.    0.61 -0.05  0.24 -0.  ]
 [ 0.    0.    0.    0.    0.24 -0.25 -0.38]
 [ 0.    0.    0.   -0.    0.   -0.38 -0.12]]
