# Singular value decomposition

The SVD of a $m \times n$ matrix $A$ is

$$
A = U \Sigma V^\star
$$

We use [numpy.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html) or [scipy.linalg.svd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) to compute this. Below we use numpy.

In [10]:
import numpy as np

Construct a random $3 \times 2$ matrix.

In [11]:
A = 2 * np.random.rand(3,2) - 1

## Reduced SVD

The reduced SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=False)
```

The function returns the $\textrm{Vh} = V^\star$.

The singular vectors and values are given by

$$
u_j = \textrm{U[:,j]}, \qquad 0 \le j < n
$$

$$
v_j = \textrm{Vh[j,:]}, \qquad 0 \le j < n
$$

$$
\sigma_j = \textrm{S[j]}, \qquad 0 \le j < n
$$

In [12]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.05242745  0.42378567]
 [ 0.82647453 -0.48983746]
 [-0.56052762 -0.76188251]]
sigma =  1.3043405743518146 0.5653402691737763
V = 
 [[-0.96593836 -0.25877227]
 [-0.25877227  0.96593836]]


$U$ is $m \times n$ and $V$ is $n \times n$.

## Full SVD

The full SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=True)
```

The singular vectors and values are given by

$$
u_j = \textrm{U[:,j]}, \qquad 0 \le j < m
$$

$$
v_j = \textrm{Vh[j,:]}, \qquad 0 \le j < n
$$

$$
\sigma_j = \textrm{S[j]}, \qquad 0 \le j < n
$$

In [15]:
U,S,Vh = np.linalg.svd(A, full_matrices=True)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.05242745  0.42378567 -0.90424392]
 [ 0.82647453 -0.48983746 -0.27748714]
 [-0.56052762 -0.76188251 -0.32456713]]
sigma =  1.3043405743518146 0.5653402691737763
V = 
 [[-0.96593836 -0.25877227]
 [-0.25877227  0.96593836]]


$U$ is $m \times m$ and $V$ is $n \times n$.