# Singular value decomposition

The SVD of a $m \times n$ matrix $A$ is

$$
A = U \Sigma V^\star
$$

We use [numpy.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html) or [scipy.linalg.svd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) to compute this. Below we use numpy.

In [6]:
import numpy as np

Construct a random $3 \times 2$ matrix.

In [7]:
A = 2 * np.random.rand(3,2) - 1

## Reduced SVD

The reduced SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=False)
```

The function returns $\textrm{Vh} = V^\star$.

The singular vectors and values are given by

\begin{align*}
u_j &= \textrm{U[:,j]}, & 0 \le j < n \\
v_j &= \textrm{Vh[j,:]}, & 0 \le j < n \\
\sigma_j &= \textrm{S[j]}, & 0 \le j < n
\end{align*}

In [8]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.68155086  0.68827138]
 [-0.63105778 -0.72476267]
 [ 0.37047874  0.03164776]]
sigma =  1.2888919729677664 0.3056580678726859
V = 
 [[ 0.34240364 -0.93955295]
 [-0.93955295 -0.34240364]]


$U$ is $m \times n$ and $V$ is $n \times n$. We can verify that $A = U \Sigma V^\star$ by computing the element-wise maximum difference

In [9]:
print(np.abs(A - U@np.diag(S)@Vh).max())

1.1102230246251565e-16


## Full SVD

The full SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=True)
```

The singular vectors and values are given by

\begin{align*}
u_j &= \textrm{U[:,j]}, & 0 \le j < m \\
v_j &= \textrm{Vh[j,:]}, & 0 \le j < n \\
\sigma_j &= \textrm{S[j]}, & 0 \le j < n
\end{align*}

In [10]:
U,S,Vh = np.linalg.svd(A, full_matrices=True)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.68155086  0.68827138  0.2485376 ]
 [-0.63105778 -0.72476267  0.27655947]
 [ 0.37047874  0.03164776  0.92830163]]
sigma =  1.2888919729677664 0.3056580678726859
V = 
 [[ 0.34240364 -0.93955295]
 [-0.93955295 -0.34240364]]


$U$ is $m \times m$ and $V$ is $n \times n$.

## Rank deficient case

Construct a random $4 \times 3$ matrix whose last column is sum of first two columns. Its rank is 2.

In [11]:
A = 2 * np.random.rand(4,3) - 1
A[:,2] = A[:,0] + A[:,1]

Compute the reduced SVD

In [12]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.84725671  0.39361274  0.35630438]
 [-0.00976908 -0.67953066  0.730543  ]
 [-0.5310112  -0.61414766 -0.5822611 ]
 [-0.0093669  -0.07829268  0.01805878]]
sigma =  1.300039169540435 0.7635167596854092 5.927603195511812e-17
V = 
 [[ 0.73153035 -0.36267067  0.57735027]
 [-0.05168316  0.8148592   0.57735027]
 [ 0.67984719  0.45218853 -0.57735027]]


We notice that one out of three singular values is zero. The number of non-zero singular values corresponds to the rank of the matrix.