# Singular value decomposition

The SVD of a $m \times n$ matrix $A$ is

$$
A = U \Sigma V^\star
$$

We use [numpy.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html) or [scipy.linalg.svd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) to compute this. Below we use numpy.

In [1]:
import numpy as np

Construct a random $3 \times 2$ matrix.

In [2]:
A = 2 * np.random.rand(3,2) - 1

## Reduced SVD

The reduced SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=False)
```

The function returns $\textrm{Vh} = V^\star$.

The singular vectors and values are given by

\begin{align*}
u_j &= \textrm{U[:,j]}, & 0 \le j < n \\
v_j &= \textrm{Vh[j,:]}, & 0 \le j < n \\
\sigma_j &= \textrm{S[j]}, & 0 \le j < n
\end{align*}

In [3]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.73230062  0.58725142]
 [-0.134568   -0.6211028 ]
 [ 0.66755319  0.51900585]]
sigma =  1.2456940406735095 0.6197107111257151
V = 
 [[-0.9958988  -0.09047417]
 [ 0.09047417 -0.9958988 ]]


$U$ is $m \times n$ and $V$ is $n \times n$.

## Full SVD

The full SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=True)
```

The singular vectors and values are given by

\begin{align*}
u_j &= \textrm{U[:,j]}, & 0 \le j < m \\
v_j &= \textrm{Vh[j,:]}, & 0 \le j < n \\
\sigma_j &= \textrm{S[j]}, & 0 \le j < n
\end{align*}

In [4]:
U,S,Vh = np.linalg.svd(A, full_matrices=True)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.73230062  0.58725142  0.34477758]
 [-0.134568   -0.6211028   0.77208986]
 [ 0.66755319  0.51900585  0.53385922]]
sigma =  1.2456940406735095 0.6197107111257151
V = 
 [[-0.9958988  -0.09047417]
 [ 0.09047417 -0.9958988 ]]


$U$ is $m \times m$ and $V$ is $n \times n$.

## Rank deficient case

Construct a random $4 \times 3$ matrix whose last column is sum of first two columns. Its rank is 2.

In [5]:
A = 2 * np.random.rand(4,3) - 1
A[:,2] = A[:,0] + A[:,1]

Compute the reduced SVD

In [6]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[ 0.03907547  0.12867712 -0.52711324]
 [-0.28494964 -0.87203441  0.25384707]
 [ 0.95751292 -0.27325583  0.07925634]
 [ 0.02111459  0.38513562  0.80711321]]
sigma =  1.9861259715664707 1.069905056712703 7.548716289322322e-18
V = 
 [[ 0.25551336 -0.77548668 -0.57735027]
 [ 0.54383448  0.6090244  -0.57735027]
 [ 0.79934785 -0.16646228  0.57735027]]


We notice that one out of three singular values is zero. The number of non-zero singular values corresponds to the rank of the matrix.