# Singular value decomposition

The SVD of a $m \times n$ matrix $A$ is

$$
A = U \Sigma V^\star
$$

We use [numpy.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html) or [scipy.linalg.svd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) to compute this. Below we use numpy.

In [16]:
import numpy as np

Construct a random $3 \times 2$ matrix.

In [17]:
A = 2 * np.random.rand(3,2) - 1

## Reduced SVD

The reduced SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=False)
```

The function returns the $\textrm{Vh} = V^\star$.

The singular vectors and values are given by

$$
u_j = \textrm{U[:,j]}, \qquad 0 \le j < n
$$

$$
v_j = \textrm{Vh[j,:]}, \qquad 0 \le j < n
$$

$$
\sigma_j = \textrm{S[j]}, \qquad 0 \le j < n
$$

In [18]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.21671993  0.93354606]
 [-0.61699789  0.09567315]
 [ 0.75653558  0.3454539 ]]
sigma =  1.7089575424847805 0.28986156370423594
V = 
 [[ 0.69502575 -0.71898484]
 [-0.71898484 -0.69502575]]


$U$ is $m \times n$ and $V$ is $n \times n$.

## Full SVD

The full SVD is given by

```
U,S,Vh = np.linalg.svd(A, full_matrices=True)
```

The singular vectors and values are given by

$$
u_j = \textrm{U[:,j]}, \qquad 0 \le j < m
$$

$$
v_j = \textrm{Vh[j,:]}, \qquad 0 \le j < n
$$

$$
\sigma_j = \textrm{S[j]}, \qquad 0 \le j < n
$$

In [19]:
U,S,Vh = np.linalg.svd(A, full_matrices=True)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.21671993  0.93354606 -0.28552447]
 [-0.61699789  0.09567315  0.78112755]
 [ 0.75653558  0.3454539   0.55526167]]
sigma =  1.7089575424847805 0.28986156370423594
V = 
 [[ 0.69502575 -0.71898484]
 [-0.71898484 -0.69502575]]


$U$ is $m \times m$ and $V$ is $n \times n$.

## Rank deficient case

Construct a random $4 \times 3$ matrix whose last column is sum of first two columns. Its rank is 2.

In [20]:
A = 2 * np.random.rand(4,3) - 1
A[:,2] = A[:,0] + A[:,1]

Compute the reduced SVD

In [21]:
U,S,Vh = np.linalg.svd(A, full_matrices=False)
print('U = \n', U)
print('sigma = ', *S)
print('V = \n', Vh.T)

U = 
 [[-0.77917876 -0.11014872 -0.48757047]
 [ 0.29934452 -0.83540078  0.06439926]
 [ 0.47840435  0.48116799 -0.39076192]
 [-0.2727684   0.24176468  0.77809568]]
sigma =  2.9491932894112627 0.8854830887185966 1.2006599845361527e-16
V = 
 [[ 0.38085711  0.72222886 -0.57735027]
 [ 0.43503998 -0.69094637 -0.57735027]
 [ 0.8158971   0.03128249  0.57735027]]


We notice that one out of three singular values is zero. The number of non-zero singular values corresponds to the rank of the matrix.